# Task 1:

Q 1. Write a function to compute 5/0 and use try/except to catch the exceptions

In [41]:
def devide_by_zero(x,y):
    try:       
        val=x/y
        print("Your anwer is:", val)
    
    except:
        print("You are deviding by value zero ")
        
devide_by_zero(5,0)

You are deviding by value zero 


Q 2. Implement a Python program to generate all sentences where subject is in
["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]


Output should come as below:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.

In [28]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

script = [(sub +" "+ verb +" "+ obj) for sub in subjects for verb in verbs for obj in objects]

for sent in script:
    print(sent)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


--------------------------------------------------------------------------------------------------------------------------------

# Task 2:

Q 1.
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [113]:

lst=[]
num=[1,2,3,4]

def matrix(num):
    N=len(num)
    for x in num:
        for i in range(N):
            lst.append(x**(N-1-i))
    array = np.array(lst)
    matrix = np.reshape(array,(4,4))    
    return matrix


print(matrix(num))


[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
